from django.urls import path
from django.views.decorators.cache import cache_page  # Import cache_page decorator
from .views import *

urlpatterns = [
    path('category-list/', cache_page(60 * 5)(EventCategoryListView.as_view()), name='event-category-list'),
    path('create-category/', cache_page(60 * 5)(EventCategoryCreateView.as_view()), name='create-event-category'),
    path('category/<int:pk>/edit/', cache_page(60 * 5)(EventCategoryUpdateView.as_view()), name='edit-event-category'),
    path('category/<int:pk>/delete/', cache_page(60 * 5)(EventCategoryDeleteView.as_view()), name='delete-event-category'),
    path('events/category/<int:category_id>/qr/', cache_page(60 * 5)(generate_qr_code), name='generate_qr_code'),
    path('events/category/google_drive/', cache_page(60 * 5)(upload_photo), name='upload_photo'),
    path('events/category/google_drive/folder/<str:folder_id>/', cache_page(60 * 5)(view_folder_contents), name='view_folder_contents'),

    path('join/<str:code>/', cache_page(60 * 5)(your_join_view), name='event-category-join'),
    path('event-create/', cache_page(60 * 5)(EventCreateView.as_view()), name='event-create'),
    path('event-list/', cache_page(60 * 5)(EventListView.as_view()), name='event-list'),
    path('event/<int:pk>/edit/', cache_page(60 * 5)(EventUpdateView.as_view()), name='event-edit'),
    path('detail/<int:pk>', cache_page(60 * 5)(EventDetailView.as_view()), name='event-detail'),
    path('delete/<int:pk>', cache_page(60 * 5)(EventDeleteView.as_view()), name='event-delete'),
    path('add-event-member/', cache_page(60 * 5)(AddEventMemberCreateView.as_view()), name='add-event-member'),
    path('join-event-list/', cache_page(60 * 5)(JoinEventListView.as_view()), name='join-event-list'),
    path('event-member/<int:pk>/remove/', cache_page(60 * 5)(RemoveEventMemberDeleteView.as_view()), name='remove-event-member'),
    path('update-status/<int:pk>/event/', cache_page(60 * 5)(UpdateEventStatusView.as_view()), name='update-event-status'),
    path('complete-event/', cache_page(60 * 5)(CompleteEventList.as_view()), name='complete-event'),
    path('create-user-mark/', cache_page(60 * 5)(CreateUserMark.as_view()), name='create-user-mark'),
    path('user-mark/', cache_page(60 * 5)(UserMarkList.as_view()), name='user-mark'),
    path('search_category/', cache_page(60 * 5)(search_event_category), name='search-event-category'),
    path('search_event/', cache_page(60 * 5)(search_event), name='search-event'),
    path('create/', cache_page(60 * 5)(create_event), name='create'),
    path('event_catogery/', cache_page(60 * 5)(event_catogery), name='event_catogery'),
    path('events_dashboard/', cache_page(60 * 5)(events_dashboard), name='events_dashboard'),
    path('gemini/', cache_page(60 * 5)(gemini), name='gemini'),
    path('group_discussion/', cache_page(60 * 5)(group_discussion), name='group_discussion'),
    path('upload_invitation/', cache_page(60 * 5)(upload_invitation), name='upload_invitation'),
    path('download-excel-template/', cache_page(60 * 5)(download_excel_template), name='download_excel_template'),
    path('task/create/<int:event_id>', cache_page(60 * 5)(create_task), name='create-task'),
    path('task/update/<int:task_id>', cache_page(60 * 5)(update_task_completion), name='update-task-completion'),
    path('tasks', cache_page(60 * 5)(task_view), name='task_view'),
    path('event/<int:event_id>/', cache_page(60 * 5)(event_detail), name='event-detail'),
    path('events/', cache_page(60 * 5)(event_list), name='event-list'),
    path('event/<int:event_id>/tasks/', cache_page(60 * 5)(event_tasks), name='event-tasks'),
    path('task/<int:task_id>/update/', cache_page(60 * 5)(update_task), name='update-task'),
    path('tasks/progress/', cache_page(60 * 5)(task_progress_view), name='task-progress'),
    path('progress/', cache_page(60 * 5)(progress), name='progress'),
    path('budget/', cache_page(60 * 5)(budget), name='budget'),
    path('vendor/', cache_page(60 * 5)(vendor), name='vendor'),
    path('download-quote/', cache_page(60 * 5)(download_quote), name='download_quote'),
]